# Generated by Django 5.2.9 on 2025-12-12 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=20, unique=True, verbose_name='학번')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('department', models.CharField(max_length=50, verbose_name='학과')),
                ('gender', models.CharField(choices=[('M', '남'), ('F', '여')], max_length=1, verbose_name='성별')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='과목명')),
                ('professor', models.CharField(blank=True, max_length=50, verbose_name='담당교수')),
                ('textbook', models.CharField(blank=True, max_length=100, verbose_name='교재명')),
                ('schedule', models.CharField(blank=True, max_length=100, verbose_name='수업시간')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='성적')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
